### ISSUE TITLE
Problem with the matrix class

### ISSUE THREAD

**Issue by NET-D3v3l0p3r** [GuyARoss/Neural-Network-cs#1]
-1-

Hello,

the matrix class has several problems.
For instance: You use a jagged-array like system to create a matrix but don't initialize the array.
The transpose and multiply methods does not work et cetera...

You can use this matrix class: https://pastebin.com/0dUuttDA to fix some problems, espacially the multiplication part.

Best regards, netdeveloper.

_

**Comment by GuyARoss** [comment]
Hey man, so this is actually a port from the original by Daniel Shiffman. Didn't build the system, but thanks a lot for contributing.
